### PR TITLE
EBT V1

### PR DESCRIPTION
**Pull request by Bamieh**
Moved code from Kibana to this repo.
Significant changes:
1. Removed `lodash.set` because it is unsafe to use for us. Replaced it by manually setting the page vars and page labels into the object reduce.
2. Created a trimmed `Logger` interface since we dont have the kbn/logger package published on npm. We expect the logger interface to have a specific signature so the types uses the minimum requirements only.
3. Version `1.0.0` will be the first used version in Kibana. currently the package is published under `0.0.x~beta` for testing the integration with kibana and the CI.
4. The telemetry endpoint `build_url` and `build_headers` are now expected as config parameters instead of having them hardcoded in the codebase. This way users of the package can change the headers or endpoint with flexiblity.
5. The build process builds the `client` and `shippers` to the root of the repo this way users of the package can import sub packages as needed. This is used in favor of a monorepo managed by turbo or such for simplicity, this should be enough to meet our needs.

### CODE REVIEW

**Comment by afharo** [comment]
One thing I noticed (that can be solved in the future) is that we don't really use the option `sendTo` in the client's constructor, do we? 😅 
https://github.com/elastic/ebt/blob/1c94399fe6553839609d084e4d217a8559744191/src/client/src/analytics_client/types.ts#L27-L30

**Comment by afharo** [comment]
> Removed lodash.set because it is unsafe to use for us. Replaced it by manually setting the page vars and page labels into the object reduce.

Ideally the list that we filter should be provided via config :)

**Review by afharo — APPROVED** [review]
LGTM! Thanks for doing this! 🧡

**Comment by Bamieh** [comment]
@afharo thanks for the review!


I've removed this and moved it to kibana
```
   sendTo: 'production' | 'staging'; 
```

and `sendTo` is set from kibana now

````
import type { BuildShipperUrlOptions, BuildShipperUrl } from '@elastic/ebt/shippers/elastic_v3/common';

/**
 * Builds the URL for the V3 API.
 */
export const createBuildShipperUrl = (sendTo: 'production' | 'staging' ): BuildShipperUrl => (urlOptions: BuildShipperUrlOptions): string => {
  const { channelName } = urlOptions;
  const baseUrl =
    sendTo === 'production'
      ? 'https://telemetry.elastic.co/'
      : 'https://telemetry-staging.elastic.co/';
  return `${baseUrl}/v3/send/${channelName}`;
};
```

inside plugin:
```
    const sendTo = this.initialConfig.sendUsageTo === 'prod' ? 'production' : 'staging';
    analytics.registerShipper(ElasticV3ServerShipper, {
      channelName: 'kibana-server',
      version: currentKibanaVersion,
      buildShipperHeaders,
      buildShipperUrl: createBuildShipperUrl(sendTo),
    });
```

**Comment by Bamieh** [comment]
> Ideally the list that we filter should be provided via config (the fields seem very Kibana-specific). But again, something that we can improve in the future :)

I will open an issue in the repo to address this in the future. i think it needs more rewiring than i would like in a "moving the package" task

**Pull request merged**
